### ISSUE TITLE
Many packages with too old EAPI

### ISSUE THREAD

**Issue by mimi89999** [marmarek/marmarek-portage#1]
Hello,
I noticed that the repo contains many packages deprecated and deprecated EAPI. They are causing errors when updating world with `sudo emerge --ask --update --newuse --deep @world`. I think that it would be best to just remove them from the repo.

**Comment by mimi89999** [comment]
https://wiki.gentoo.org/wiki/EAPI

**Comment by mimi89999** [comment]
[emerge-log.txt](https://github.com/marmarek/marmarek-portage/files/6569275/emerge-log.txt)

**Comment by marmarek** [comment]
I don't really maintain this repository anymore. A lot of packages here (all of them?) are quite outdated and may include unpatched security vulnerabilities, so I'd recommend against using it. I'm adding appropriate note to the readme now.
If you want to keep using it, I strongly recommend making a fork and applying required changes there instead.
